site_name: LNL3D Wiki
site_url: https://lnl3d.github.io 

site_description: This is a site dedicated to LNL3D 3D printers. Here you can find all sorts of information about our line of printers, as well as how to operate and repair them.

#theming and features
theme:
  palette:
    scheme: default
    primary: teal
    accent: blue
  name: material
  logo: assets/LNL.png
  features: 
    - navigation.instant
    - navigation.tracking
#  - navigation.tabs
 #   - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github

extra: 
    homepage: https://lnl3d.com


#navigation

nav:
  - index.md 
  - Tenlog Specifications: TenlogSpecifications.md
  - updatingsoftware.md
  - Vulcan Firmware Guide:
    - Overview: firmware/index.md
  - about.md

plugins:
  - mkdocs-video
  - search
    
#repo
repo_name: LNL3D
repo_url: https://github.com/LNL3D

#extensions

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
